# GitHub Dependabot configuration file

version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain dependencies for maven
  - package-ecosystem: "maven"
    directory: "/maven-plugins"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "com.fasterxml.jackson.core:jackson-databind"
        # This version is used in the resolver tests and should not be updated
        versions: ["2.11.1"]

  # Maintain dependencies for gradle
  - package-ecosystem: "gradle"
    directory: "/gradle-plugins"
    schedule:
      interval: "daily"

  # Maintain dependencies for bundler
  - package-ecosystem: "bundler"
    directory: "/docs"
    schedule:
      interval: "daily"
