package aQute.bnd.service.diff;

public enum Type {
	BUNDLE, API, MANIFEST, PACKAGE, CLASS, INTERFACE, EXTENDS, IMPLEMENTS, FIELD, METHOD, ANNOTATION, PROPERTY, RESOURCE, CUSTOM, CLAUSE, HEADER, PARAMETER, CLASS_VERSION, RESOURCES, CONSTANT; 
}
