package name.neilbartlett.eclipse.bndtools.editor.model;

public class ExportedPackage {
	
	private final String packageName;
	private final String version;

	public ExportedPackage(String packageName, String version) {
		this.packageName = packageName;
		this.version = version;
	}

	public String getPackageName() {
		return packageName;
	}

	public String getVersion() {
		return version;
	}

	/*
	 * (non-Javadoc)
	 * Generated by Eclipse
	 * @see java.lang.Object#hashCode()
	 */
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((packageName == null) ? 0 : packageName.hashCode());
		result = prime * result + ((version == null) ? 0 : version.hashCode());
		return result;
	}

	/*
	 * (non-Javadoc)
	 * Generated by Eclipse
	 * @see java.lang.Object#equals(java.lang.Object)
	 */
	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ExportedPackage other = (ExportedPackage) obj;
		if (packageName == null) {
			if (other.packageName != null)
				return false;
		} else if (!packageName.equals(other.packageName))
			return false;
		if (version == null) {
			if (other.version != null)
				return false;
		} else if (!version.equals(other.version))
			return false;
		return true;
	}
	
	
}
