package aQute.bnd.maven;

import java.io.*;
import java.util.*;

import aQute.bnd.osgi.*;
import aQute.lib.utf8properties.*;

public class PomPropertiesResource extends WriteResource {
	private final Properties	pomProperties;
	private final String		where;

	public PomPropertiesResource(PomResource pomResource) {
		pomProperties = new UTF8Properties();
		pomProperties.setProperty("groupId", pomResource.getGroupId());
		pomProperties.setProperty("artifactId", pomResource.getArtifactId());
		pomProperties.setProperty("version", pomResource.getVersion());
		where = pomResource.getWhere().replaceFirst("(?<=^|/)pom\\.xml$", "pom\\.properties");
	}

	public String getWhere() {
		return where;
	}

	@Override
	public long lastModified() {
		return 0;
	}

	@Override
	public void write(OutputStream out) throws IOException {
		pomProperties.store(out, "Generated by bnd");
	}
}
